# Generated by Django 5.2.6 on 2025-09-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='№')),
                ('time', models.CharField(max_length=20, verbose_name='Час катання')),
                ('name', models.CharField(max_length=20, verbose_name='Назва атракціону')),
                ('min_age', models.IntegerField(verbose_name='Мінімальний вік')),
                ('zone', models.IntegerField(verbose_name='Зона розташування')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='№')),
                ('name', models.CharField(max_length=20, verbose_name="Ім'я")),
                ('surname', models.CharField(max_length=20, verbose_name='Прізвище')),
                ('age', models.IntegerField(verbose_name='Вік')),
                ('registration_date', models.DateField(verbose_name='Дата реєстрації')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='№')),
                ('name', models.CharField(max_length=20, verbose_name="Ім'я")),
                ('surname', models.CharField(max_length=20, verbose_name='Прізвище')),
                ('age', models.IntegerField(verbose_name='Вік')),
                ('address', models.CharField(max_length=100, verbose_name='Адреса')),
            ],
        ),
    ]
